"""
Brand List for Dog Food Products

This module contains the normalized list of brands used for brand detection.
Update this list as needed when new brands are discovered.

Usage:
    from app.processors.brands import BRANDS, NORMALIZED_BRANDS
    
    # Use BRANDS for original case-sensitive brand names
    # Use NORMALIZED_BRANDS for lowercase matching
"""

# Brand list - Add brands here as you discover them
# Order matters: longer/more specific brands should come first
# (e.g., "Purina Pro Plan" before "Purina")
BRANDS = [
    "By Chewy",
    "+PlusPET",
    "1-TDC",
    "10 Strawberry Street",
    "2 Hounds Design",
    "21st Century Essential Pet",
    "3 Dog Pet Supply",
    "3 Moms Organics",
    "360 Pet Nutrition",
    "4 Cats & Dogs",
    "4-Legger",
    "4CYTE",
    "4Knines",
    "5Strands",
    "A Better Treat",
    "A Pet Hub",
    "A Pet's Life",
    "A Strong Heart",
    "a tail we could wag",
    "Absolutely Clean",
    "ACANA",
    "Accent Fashion",
    "Acepromazine",
    "Acepromazine Maleate Compounded",
    "Acetazolamide",
    "Acetazolamide Compounded",
    "ActivPhy",
    "ActivTreats",
    "Adams",
    "ADC Houndstone & Co.",
    "Addiction",
    "Adequan Canine",
    "Adirondack",
    "ADORE Pet",
    "Advance Pet",
    "Advance Pet Product",
    "Advantage",
    "Advantage II",
    "Advantage Multi",
    "Advantus",
    "Adventure Medical Kits",
    "AdVet Hygienics",
    "Advocate",
    "Aetertek",
    "Affordable Pet Labs",
    "AFreschi",
    "After The Hunt",
    "Against the Grain",
    "Agon",
    "Aikeep",
    "Air Scense",
    "Air Wick",
    "AirDoctor",
    "Airpet",
    "AIRROBO",
    "Aivituvin",
    "Alaska Naturals",
    "Albatross Health New England",
    "Albon",
    "Albuterol",
    "Alcott",
    "Alendronate Compounded",
    "Alfie Pet",
    "Alkazone",
    "All American Canine",
    "All Four Paws",
    "Allerpet",
    "allforpaws",
    "Allisandro",
    "Allopurinol",
    "Allopurinol Compounded",
    "Almo Nature",
    "Aloeplus",
    "Alpha Dog Nutrition",
    "Alpha Dog Series",
    "Alpha Paw",
    "AlphaTRAK",
    "Altira",
    "Aluminum Hydroxide Compounded",
    "Always Full",
    "ALZOO",
    "Amana Grace",
    "Amantadine HCl",
    "Amantadine HCl Compounded",
    "Amazing Dog Treats",
    "Amazing Nutritionals",
    "Amazonia",
    "American BioSciences",
    "American Journey",
    "American Kennel Club",
    "American Kennel Club Treats",
    "American Natural Premium",
    "American Pet Food",
    "AmeriHome",
    "Ami",
    "Amici Pet",
    "Amikacin/Ketoconazole/Triamcinolone (AKT) Compounded",
    "AminAmend",
    "AminAvast",
    "Aminocaproic Acid Compounded",
    "Amitriptyline",
    "Amitriptyline HCl Compounded",
    "Amlodipine",
    "Amlodipine Compounded",
    "Amoxi-Drops",
    "Amoxi-Tabs",
    "Amoxicillin",
    "Amoxicillin and Clavulanate Potassium",
    "Ampicillin",
    "Ample Nutrition",
    "Amzey",
    "Andis",
    "Andover Healthcare",
    "Angel",
    "Angels' Eyes",
    "Angry Orange",
    "Animal Essentials",
    "Animal Health Solutions",
    "Animal Necessity",
    "Animal Nutritional Products",
    "AnimalBiome",
    "Animals Like Us",
    "Animax",
    "AniMed",
    "Anipryl",
    "Aniwell",
    "Annamaet",
    "Annie's Pooch Pops",
    "Antinol Plus",
    "Antirobe",
    "Aosom",
    "AOSTIRMOTOR",
    "Apex Plus",
    "Apocaps",
    "Apoquel",
    "Applaws",
    "Arava Dead Sea Pet Spa",
    "Archstone Pets",
    "Archway",
    "Arden",
    "Arenti",
    "Arf Pets",
    "Ark Naturals",
    "Arkus",
    "Arlee Home & Pet",
    "Arlo",
    "Arm & Hammer",
    "Arm & Hammer Litter",
    "Arm & Hammer Products",
    "Armarkat",
    "ArmOR Hand",
    "Arnall's Naturals",
    "Aroma Car",
    "Aroma Retail",
    "Arrowleaf Pet by NaturPet Inc.",
    "Artemis",
    "Arterra",
    "Artisan Inspired",
    "Artisanal Paws",
    "Arya Sit",
    "As Seen on TV",
    "ASPCA",
    "Aspen Pet",
    "Aspirin",
    "Aspirin Compounded",
    "Assisi Animal Health",
    "Atenolol",
    "Atenolol Compounded",
    "ATIFBOP",
    "Atomic Bubbles",
    "Atopica",
    "Atopivet",
    "Atrix",
    "Atta Boy",
    "Augie Bones",
    "aumuca",
    "Aunt Fannie's",
    "Austin and Kat",
    "Autoslide",
    "Aventix",
    "AvoDerm",
    "Awesome Pawsome",
    "Awoo",
    "Azathioprine",
    "Azathioprine Compounded",
    "Azestfor",
    "Azithromycin",
    "Azithromycin Compounded",
    "B&G Martin",
    "Bab'in",
    "Babyliss Pro Pet",
    "Back on Track",
    "Badgley Mischka",
    "Badlands Ranch",
    "Bag Balm Pet",
    "Bags on Board",
    "Bailey Cat Co.",
    "Balanced Breed",
    "BalanceGI",
    "bali & pari",
    "Balto",
    "Banixx",
    "Barbour",
    "Barefoot Dreams",
    "BARK",
    "Bark & Clean",
    "Bark and Slumber",
    "Bark and Whiskers",
    "Bark Bistro Company",
    "Bark Bone",
    "Bark Boosters",
    "Bark Brite",
    "Bark Collar",
    "Bark Potty",
    "Bark&Spark",
    "Bark2Basics",
    "Barkful",
    "Barking Buddha",
    "BarksBar",
    "Barkworthies",
    "Barn Dog",
    "Barpor",
    "Barrier",
    "Basic Animal Health",
    "Basic Spirit",
    "Baskerville",
    "Bass Brushes",
    "Baxter",
    "Baxter Boy",
    "Bay Island Sportswear",
    "Baytril",
    "Be Wild",
    "Be:Loved",
    "Bear Bear",
    "Bearwood Essentials",
    "Beauty By Benjamin",
    "Beautyrest",
    "Because It's Better",
    "Bedsure",
    "BedVoyage",
    "Beefeaters",
    "beeNbkks",
    "Beg & Barker",
    "Beggar Dog",
    "Beggin'",
    "Behrens",
    "Bell + Howell",
    "Bella & Pal",
    "BellyGuard",
    "Bellylabs",
    "Beloved Pets",
    "Ben's",
    "Benazepril",
    "Benazepril HCl Compounded",
    "Benazepril HCl/Furosemide/Pimobendan Compounded",
    "Bench & Field",
    "Bencmate",
    "Benebone",
    "Benny Bullys",
    "Bergan",
    "Bern Dog Brand",
    "Bernie's",
    "Bespoke Paws",
    "Bessie + Barnie",
    "Best Bully Sticks",
    "Best Dog Chews",
    "Best Friend Mobility",
    "Best Friend Services",
    "Best Friends by Sheri",
    "Best Paw Nutrition",
    "Best Pet Supplies",
    "Best Shot",
    "Besties",
    "Better Belly",
    "Better Blanket",
    "Better Sporting Dogs",
    "BetterBone",
    "Beurer",
    "beyondGREEN",
    "Big Barker",
    "Big Dog Antler Chews",
    "Big Red",
    "Big Sky Antler Chews",
    "Bil-Jac",
    "BingoPaw",
    "Bio-Groom",
    "BioBag",
    "Bioline",
    "Biologic Vet",
    "Biomox",
    "Bionic",
    "BioPup",
    "BioSilk",
    "Birdie & Louie",
    "Bite Force",
    "Bitebuster",
    "BIXBI",
    "Black Gold",
    "Black Sheep Organics",
    "Black+Decker",
    "Blackwood",
    "Blazin",
    "Blow Pop",
    "Blue Buffalo",
    "Blue Buffalo Natural Veterinary Diet",
    "Blue Dog Bakery",
    "Blue Ridge Naturals",
    "Blue-9",
    "Blueair",
    "Blueberry Pet",
    "Bluegrass Animal Products",
    "Boat to Bowl Pet Food",
    "Bobbi Panter",
    "Bocce's Bakery",
    "Body Glove",
    "Bona",
    "Bone Dry",
    "Bones & Chews",
    "BONIES",
    "Bonkers",
    "Bonne et Filou",
    "Bonza",
    "Booda",
    "Boone",
    "Boops Pets",
    "Booster Bath",
    "BOS",
    "Boshel",
    "Boss Dog",
    "Boss Pet",
    "Botanical Animal Flower Essences",
    "Both Tails",
    "Boulevard",
    "Bousnic",
    "Bovidr Laboratories",
    "Bow Wow Labs",
    "Bow Wow Ranch",
    "Bow-Wow Pet",
    "Boxiecat",
    "Brave Paws",
    "Bravecto",
    "Bravo Paws",
    "Bravo!",
    "BravoWalk",
    "Breathe Naturally",
    "Brecknell",
    "Breed Essentials",
    "Breezy Tail",
    "Bright Planet Pet",
    "Brightkins",
    "Brilliant",
    "Brindle",
    "BRONZEDOG",
    "Brooklyn Pet Gear",
    "Browning",
    "Brutus & Barnaby",
    "Brutus Broth",
    "bSerene",
    "Bubba Rose Biscuit Co.",
    "Bubble Lick",
    "Buck Bone Organics",
    "Buckle-Down",
    "Buddy Belts",
    "Buddy Biscuits",
    "Buddy Buddy",
    "Buddy Jack's",
    "Buddy Wash",
    "BuddyBiotics",
    "Buddycare",
    "BuddyRest",
    "Budesonide",
    "Budesonide Compounded",
    "Budweiser",
    "Bueteka",
    "Buff Brite",
    "Buffalo Range",
    "BugMD",
    "Bulldogology Pet Solutions",
    "BullHug",
    "BulliBone",
    "Bully Bunches",
    "Bully Max",
    "Bully Sticks",
    "BULLYMAKE",
    "Bullysticks And More!",
    "BullyYaker",
    "Bundle x Joy",
    "Bungalow Flooring",
    "Burley",
    "Burt's Bees",
    "Busch Light",
    "Buspirone",
    "Buspirone HCl Compounded",
    "Busy Bone",
    "Butcher Shop",
    "Butcher's Naturals",
    "C&F",
    "Cadet",
    "Cafe Nara",
    "Caghash",
    "Caitec",
    "Calcitriol Compounded",
    "Caldwell's Pet Supply Co.",
    "Caledon Farms",
    "California Costumes",
    "California Tea House",
    "Callie's Kitchen",
    "Calm Paws",
    "Canada Fresh",
    "Canada Pooch",
    "Canalevia-CA1",
    "CANIDAE",
    "Canine Canyon",
    "Canine Carry Outs",
    "Canine Caviar",
    "Canine Chews",
    "Canine Cravers",
    "Canine Matrix",
    "Canine Naturals",
    "Canine's Choice",
    "CanineActiv",
    "Canisource",
    "CANNA COMPANION",
    "Canny",
    "Capstar",
    "Carbona",
    "Cardalis",
    "Cardinal Gates",
    "CardioMAX",
    "Carhartt",
    "Carlson Pet Products",
    "Carolina Pet",
    "Carolina Prime Pet",
    "Carprieve",
    "Carprofen",
    "Carprofen Compounded",
    "CarSafe",
    "Carson Industries",
    "Caru",
    "Casfuy",
    "Casper",
    "Casual Home",
    "Cat Mate",
    "Cat-in-the-bag",
    "Cat-Man-Doo",
    "CatGuru",
    "Cathedral Art",
    "Catit",
    "Cedarcide",
    "Cefpoderm",
    "Cefpodoxime",
    "CELEBRATIONS",
    "Celecoxib Compounded",
    "CellBIO",
    "Cephalexin",
    "Cerenia",
    "Cesar",
    "Cesicia",
    "Cestex",
    "Cetirizine HCl Compounded",
    "Chai's Choice",
    "Charlee Bear",
    "Charlie's Doggie Bag",
    "Charlotte's Web",
    "Charmy",
    "Chasing Our Tails",
    "CheckUp",
    "Cheerble",
    "Chemical Guys",
    "Chew + Heal",
    "Chew King",
    "Chew'ems",
    "ChewDoo",
    "CHEWFFON",
    "Chewmasters",
    "Chewmate",
    "ChewMax Pet Products",
    "chewmeter",
    "Chewy",
    "Chewy Louie",
    "CHI",
    "Chicken Soup for the Soul",
    "Chill Paws",
    "Chilly Dog",
    "Chipolo",
    "Chippin",
    "Chlorambucil Compounded",
    "Chloramphenicol",
    "Chloramphenicol Compounded",
    "ChloraSeb",
    "Chlorpheniramine",
    "Chlorpheniramine Maleate Compounded",
    "Choco Nose",
    "ChomChom Roller",
    "Chomp'ems",
    "Chomper",
    "Chondro-FLEX",
    "Chris Christensen",
    "Chuckit!",
    "Chumajor",
    "ChurpiChews",
    "Cidofovir Compounded",
    "Cimetidine",
    "Ciprofloxacin",
    "Circle T",
    "Cisapride Compounded",
    "Citra Solv",
    "Citrus Magic",
    "Clarithromycin Compounded",
    "Claudia's Canine Bakery",
    "Clavacillin",
    "Clavamox",
    "Clean Coats",
    "Clean Go Pet",
    "Clean Republic",
    "CleanSmart",
    "Clear Air",
    "ClearFur",
    "Cleverpup",
    "Clifford",
    "ClindaCure",
    "Clindamycin",
    "Clindamycin Compounded",
    "Clintabs",
    "Clomicalm",
    "Clomipramine HCl Compounded",
    "Clomipramine Hydrochloride",
    "Clopidogrel Bisulfate",
    "Clopidogrel Compounded",
    "Clorox",
    "Closer Pets",
    "Cloud Star",
    "Club Nine Pets",
    "CLUELESS",
    "Coachi",
    "Coastal Pet Products",
    "Coco and Luna",
    "COCOYO",
    "Colapz",
    "Colchicine Compounded",
    "Coleman",
    "CollarDirect",
    "Colognes For Pets",
    "Colorado Naturals",
    "Colorfil",
    "Comfort Soft",
    "ComfortFlex",
    "Comfortis",
    "COMFURT COLLAR",
    "Command Pet Products",
    "Companion Candles",
    "Companion Gear",
    "Contone",
    "Controlled Labs Pets",
    "Cool Pup",
    "Cool Runners",
    "Coolaroo",
    "Copatchy",
    "Cordaroys",
    "Coromega",
    "Cosmo Furbabies",
    "Cosmo's Snack Shack",
    "Couch Guard",
    "Country Brook Design",
    "Country Brook Petz",
    "Country Kitchen",
    "Country Vet Naturals",
    "Cowboy Magic",
    "Cowboy's",
    "Cox Vet Lab",
    "Coziwow",
    "Cozy Tails",
    "Cozypal",
    "CozyVest",
    "CP Basics",
    "CPR Cleaning Products",
    "Cranberry D-Mannose",
    "Cranimals",
    "Crave",
    "Crazy Dog",
    "Creative Science",
    "Credelio",
    "Credelio Quattro",
    "Critta Fitta",
    "Crumps Natural's",
    "Crumps' Naturals",
    "CSI",
    "Cube",
    "Curicyn",
    "Curli",
    "Curry on a Stik",
    "Custom Personalization Solutions",
    "CuteBone",
    "Cutter",
    "Cyclavance",
    "Cyclosporine",
    "Cyclosporine Compounded",
    "Cyclosporine/Tacrolimus Compounded",
    "Cyproheptadine",
    "Cyproheptadine HCl Compounded",
    "D-Art Collection",
    "Dakota 283",
    "Dakpets",
    "Dandylion",
    "DANISH DESIGN",
    "Dantrolene Sodium Compounded",
    "Darford",
    "Dave's Pet Food",
    "Davis",
    "Dawnspaces",
    "DDMOMMY",
    "De' Vora",
    "Decflow",
    "Decoquinate Compounded",
    "Deley Naturals",
    "Delilah Home",
    "Delomo",
    "Demecarium Bromide Compounded",
    "Denestra",
    "Dental Fresh",
    "DentaLife",
    "Deo Doo",
    "Deramaxx",
    "Derby Originals",
    "Derm-Tabs",
    "Derma-Clens",
    "DermaBenSs",
    "DERMagic",
    "DermAllay",
    "DermaLyte",
    "Dermapaw",
    "Dermoscent",
    "Design Imports",
    "Designer Pet Products",
    "Desmopressin",
    "Destructables",
    "Details",
    "Dexamethasone",
    "Dexamethasone Compounded",
    "Dexas Popware for Pets",
    "Dexasone",
    "Dexypaws",
    "Diamond",
    "Diane",
    "DiatomaceousEarth",
    "Diazoxide Compounded",
    "Diclofenac",
    "Dicloxacillin",
    "Diethylstilbestrol Compounded",
    "Dig Defence",
    "Digby & Fox",
    "Digger's",
    "Diggin' Your Dog",
    "Diggs",
    "Digoxin",
    "DILT-XR",
    "Diltiazem",
    "Diltiazem HCl Compounded",
    "Dingo",
    "Dinovite",
    "Diphenhydramine",
    "Diphenhydramine HCl Compounded",
    "Dirt Devil",
    "Disney",
    "Disney Christmas Bark",
    "Disney Classics",
    "Disney Glad Wags",
    "DISNEY PIXAR",
    "DISNEY PRINCESS",
    "Disney Table Scraps",
    "Divine Canine",
    "DNA My Dog",
    "Doc Roy's",
    "Dog Bandana Co.",
    "DOG By Dr Lisa",
    "Dog Chow",
    "Dog Delights",
    "Dog Fashion Spa",
    "Dog Friendly Co.",
    "Dog Gone Smart",
    "DOG H20 & CAT H20",
    "Dog Helios",
    "DOG iD",
    "Dog is Good",
    "Dog Mamma's",
    "Dog Mate",
    "Dog Pain Away",
    "Dog Palace",
    "Dog Rocks",
    "Dog Tag Art",
    "Dog Treat Naturals",
    "Dog Whisperer",
    "Dog's Love",
    "DogBuddy",
    "DogCare",
    "doggiCLEEN",
    "Doggie Dailies",
    "Doggie Design",
    "Doggie Doo Drain",
    "Doggie Dooley",
    "Doggie Stylz",
    "Doggie Walk Bags",
    "DoggieLawn",
    "Doggijuana",
    "DogGoods Do Good",
    "Doggy Do Good",
    "Doggy Tales",
    "DoggyRade",
    "Dogipot",
    "Dogit",
    "Dogline",
    "DOGNESS",
    "Dogs & Cats & Co.",
    "Dogs Rock",
    "Dogsee",
    "DogStar",
    "Dogswell",
    "Dogtor Doolittle",
    "Dogtra",
    "DOK",
    "Dole",
    "Dolly Pet",
    "Domes Pharma",
    "DOOG",
    "Dooloop",
    "Dorzolamide",
    "Dots",
    "Douxo",
    "Douxo S3",
    "Downtown Barkery",
    "Downtown Pet Supply",
    "Doxepin",
    "Doxidyl",
    "Doxycycline",
    "Doxycycline Compounded",
    "Dr Woow",
    "Dr. Bill's Pet Nutrition",
    "Dr. Brite",
    "Dr. Buzby's",
    "Dr. Gabby Wild",
    "Dr. Gary's Best Breed",
    "Dr. Goodpet",
    "Dr. Joseph's VetPro Complete",
    "Dr. Maggie by NaturPet Inc.",
    "Dr. Mercola",
    "Dr. Paws Choice",
    "Dr. Pol",
    "Dr. Sniff",
    "Dr. Tim's",
    "DrainShroom",
    "Dream Black Label",
    "DreamBone",
    "Dremel",
    "Dreo",
    "Drillbrush",
    "Droncit",
    "Drontal",
    "Drymate",
    "DT Systems",
    "Dubble Bubble",
    "Ducks Unlimited",
    "Duke-N-Boots",
    "Dumper Cables",
    "Dupray",
    "DuraForce",
    "Duralactin",
    "Durkha",
    "Durvet",
    "Dynarex",
    "Dyson",
    "E&S PETS",
    "Eagle Pack",
    "Earth Animal",
    "Earth Care",
    "Earth Heart",
    "Earth Rated",
    "Earthbath",
    "Earthborn Holistic",
    "Earthly",
    "Easotic",
    "Eat Play Wag",
    "EcoKind",
    "EcoLeo",
    "EcoLogic",
    "ECOS for Pets!",
    "EcoSMART",
    "EcoSpaw",
    "EcoStrong",
    "Ecovacs",
    "Eddie Bauer",
    "EDTA Compounded",
    "Educator",
    "EicosaDerm",
    "Einstein Pets",
    "Elanco",
    "EliteField",
    "Elixir Kitchens",
    "Elle",
    "els pet",
    "Embark",
    "Embark Harness Co.",
    "Emerald Pet",
    "Emmy's Best Pet Products",
    "ENABOT",
    "Enalapril",
    "Enalapril Maleate Compounded",
    "Enalapril Maleate/Furosemide/Pimobendan Compounded",
    "Enalapril Maleate/Pimobendan Compounded",
    "Endosorb",
    "Endura Flap",
    "Enjoy Yums",
    "Enrofloxacin",
    "Enrofloxacin / Ketoconazole / Triamcinolone (EKT) Compounded",
    "Enrofloxacin Compounded",
    "Entyce",
    "Envirogroom",
    "EOX",
    "Epi-Pet",
    "EpiKlean",
    "EpiPaws",
    "Epizyme",
    "Equa Holistics",
    "EQyss Grooming Products",
    "Ernie Els Pet Products",
    "Erythromycin Compounded",
    "Espree",
    "Essence",
    "Estradiol",
    "Ethical Pet",
    "Etna",
    "Etodolac",
    "Etta Says!",
    "Eufy",
    "Eukanuba",
    "Eureka",
    "Euro-Dog",
    "Evanger's",
    "Evercare Pet Plus",
    "EVERFETCH",
    "EverRoot",
    "Every Day Naturals",
    "Evolution",
    "Evolve",
    "Exclusively Dog",
    "Exel",
    "Extend",
    "Extreme Dog Fence",
    "Eyenimal",
    "EyeVac",
    "EYS",
    "EZ Change",
    "EZ Groom",
    "EzyDog",
    "Fab Dog",
    "fabdog",
    "Fable Pets",
    "Fabulous Fido",
    "Fairela",
    "Famciclovir",
    "Famciclovir Compounded",
    "Famotidine",
    "Famotidine Compounded",
    "Fantastic Dog Chews",
    "Farm Dog",
    "Farm Dog Naturals",
    "Farmina",
    "Farmina Vet Life",
    "Farmland Traditions",
    "Fat Cat",
    "FC Sturtevant",
    "FEANDREA",
    "FearLess Pet",
    "Febreze",
    "Feedoo",
    "Fenbendazole Compounded",
    "Fera Pets",
    "Ferplast",
    "Ferrera Farms",
    "Fetch For Pets",
    "Fi",
    "FIDA",
    "Fido Fave",
    "Fido's Bone Broth",
    "Field Dog",
    "Fieldcrest Farms",
    "Fifth & Fido",
    "FifthPulse",
    "Fikas Freaky Friends",
    "Filter",
    "Filtrete",
    "Finest for Pets",
    "Finfare",
    "Finley's",
    "Finn",
    "FinNero",
    "Firocoxib",
    "Firox",
    "First Light Farms",
    "First Saturday Lime",
    "Firstmate",
    "FISHER PRICE",
    "FitPAWS",
    "Fizzion",
    "FLAVORS",
    "Flea Away",
    "Fleabusters",
    "Flexi",
    "Flexipan",
    "Flexpet",
    "Flexprofen",
    "Flipo",
    "Floofball",
    "Floortex",
    "Flora-Pectin",
    "florence by mills",
    "Flourish",
    "Fluconazole",
    "Fluconazole Compounded",
    "Fludrocortisone",
    "Fludrocortisone Acetate Compounded",
    "FluentPet",
    "Fluff Trough",
    "Fluoxetine",
    "Fluoxetine HCl Compounded",
    "Flurbiprofen Sodium Compounded",
    "Flydog",
    "Flying Pawfect",
    "Flying Pig Grooming",
    "Flys-Off",
    "Fooey",
    "Forager's Feed",
    "forePets",
    "Forever Puppy",
    "Formula Raw",
    "Forticept",
    "Forza10",
    "Foster",
    "fouFIT",
    "Found My Animal",
    "Four Paws",
    "Fox Chapel Publishing",
    "Freely",
    "FreezeTag",
    "Frenchies vs Everybody",
    "Fresh Field",
    "Fresh Wave",
    "Freshpet",
    "Friday's Dog",
    "Friends Forever",
    "FriendshipCollar",
    "Fringe Studio",
    "Frisco",
    "Front Row",
    "Frontline Gold",
    "Frontline Plus",
    "Frontline Shield",
    "Frontpet",
    "Fruitables",
    "Fuel Good",
    "FUKUMARU",
    "Full Moon",
    "FullBucket Health",
    "Funky Flies",
    "FunXplore",
    "Fur Valley",
    "Fur-Zoff",
    "FUR4",
    "FURemover",
    "Furesh",
    "FurHaven",
    "Furmate",
    "FurMe",
    "FURminator",
    "Furosemide",
    "Furosemide Compounded",
    "Furosemide/Pimobendan Compounded",
    "FurRealz",
    "Furrfighters",
    "Furry Republic",
    "Furry Twinz",
    "FurryFido",
    "Furvor",
    "FurZapper",
    "FUUFOME",
    "Fuzzwoof",
    "FuzzYard",
    "FXW",
    "Gabapentin",
    "Gabapentin Compounded",
    "Gaines Family Farmstead",
    "Galliprant",
    "Gamma2",
    "Gapzer",
    "Garfield",
    "Garmin",
    "Gather",
    "Geeni",
    "Gen7Pets",
    "Genesis",
    "Gentacalm",
    "Gentamicin",
    "Gentamicin/Ketoconazole/Triamcinolone (GKT) Compounded",
    "Gentle Creatures",
    "Gentle Giants",
    "Germ Guardian",
    "Gerrard Larriett Aromatherapy Pet Care",
    "Get Joy",
    "Get Naked",
    "GF Pet",
    "Gigwi",
    "Giovanni",
    "Girl With The Dogs",
    "Glacier Peak Holistics",
    "Glad",
    "Glad for Pets",
    "GlocalMe",
    "Glyde Mobility Chews",
    "GMASON",
    "GMI",
    "Gnawsome",
    "GNC Pets",
    "Go Pet Club",
    "Go! Solutions",
    "GoDog",
    "GoGo Pet Products",
    "Goldie",
    "Gonesh",
    "Gonzo Natural Magic",
    "GOO-EEZ",
    "Gooby",
    "Good 'n' Fun",
    "Good 'n' Tasty",
    "Good Boy",
    "Good Natured Brand",
    "Good Pet Kitchen",
    "Good Salt Pet",
    "Good Trouble",
    "GoodGrowlies",
    "Googipet",
    "Google",
    "GOOPAWS",
    "GoTags",
    "Gotta Go Grass",
    "Gotta Potty",
    "Gou Gou Pets",
    "GoughNuts",
    "Grab-N-Gone",
    "Grandma Lucy's",
    "Grateful Pawz",
    "Gravy Train",
    "Great Jack's",
    "Greater Wild",
    "Green Coast Pet",
    "Green Cow",
    "Green Lifestyle",
    "Greenbone",
    "Greenies",
    "Griggles",
    "Grillerz",
    "Griseofulvin Compounded",
    "Grizzly",
    "Groomer's Stone",
    "Groovies",
    "GroovyPets",
    "GROWL",
    "Grrreen",
    "Guardian Gear",
    "GuardMasterIII",
    "GUNNER",
    "GURU",
    "H&H Pets",
    "H.VERSAILTEX",
    "Hakuna Pets",
    "Halinfer",
    "Halo",
    "Halo Collar",
    "Halt!",
    "Halti",
    "Hamilton",
    "HANAMYA",
    "HandsOn",
    "Hanzi Pets",
    "happimess",
    "Happy & Polly",
    "Happy Dookies",
    "Happy Go Healthy",
    "Happy Hips",
    "Happy Hoodie",
    "Happy Hounds",
    "Happy Howie's",
    "Happy Howl",
    "Happy Jack",
    "Happy Olly",
    "Happy Paws",
    "Happy Tails",
    "HappyCare Textiles",
    "Hare of the Dog",
    "HarperCollins Publishers",
    "Harry Barker",
    "HARRY POTTER",
    "Hartz",
    "Harvest Moon",
    "HASHIMOTO",
    "Hauspanther",
    "Haute Diggity Dog",
    "Havniva",
    "HDP",
    "Headlight Harness",
    "Healers",
    "Health Extension",
    "Healthfuls",
    "Healthy Breeds",
    "Healthy Dogma",
    "Healthy Paw Life",
    "Healthy Pup",
    "Healthy Solutions for Pets",
    "Healthy Woof",
    "Healthy World",
    "Healthybud",
    "Heartgard",
    "Heartland Antlers",
    "Heat Storm",
    "Heather's Heroes",
    "Heavenly Hounds",
    "Heckova!",
    "Heeyoo",
    "Heininger",
    "Hello Kitty",
    "Hemp Heros",
    "Hemp Well",
    "Hempz Petz",
    "Herbsmith",
    "Herding Buddy",
    "Herm Sprenger",
    "Hertzko",
    "heyLove",
    "Hi-Line Gift",
    "HICC PET",
    "Hiddin",
    "High Tech Pet Products",
    "Highwave",
    "Hill's",
    "Hill's Prescription Diet",
    "Hill's Science Diet",
    "Hillside Farms",
    "Himalayan Pet Supply",
    "Hip Doggie",
    "Hippo Sak",
    "Hittite",
    "Hoistspark",
    "HOLI",
    "Holistic Select",
    "Holistic Vet Blend",
    "HOMAGICO",
    "HomeoPet",
    "HomeRunPet",
    "Homespice",
    "Honest Paws",
    "Honest To Goodness",
    "Honey I'm Home",
    "HoneyCare",
    "HoneyCure",
    "HONEYGUARDIAN",
    "Honeywell",
    "HOOEY",
    "Hoover",
    "HOOZA",
    "Horizon",
    "Horsepower",
    "Horseware Ireland",
    "Hot Shot",
    "Hotel Doggy",
    "HOTSPOT PETS",
    "Hound & Gatos",
    "Hound2O",
    "Houndstone",
    "House Parts, Inc.",
    "Howl's Kitchen",
    "Hownd",
    "HPZ",
    "ht-pet",
    "Huggibles",
    "HuggleHounds",
    "Huggy Tuggy",
    "HUGO & HUDSON",
    "HugSmart Pet",
    "Humulin",
    "Hunger for Words",
    "Hungry Paws",
    "Huntaway",
    "Huntley Pet",
    "Hurtta",
    "Hustle & Blush",
    "Huxley & Kent",
    "Hyalogic",
    "HyCoat",
    "Hydra",
    "Hydralazine",
    "Hydro-Stat! Spray",
    "Hydrocortisone",
    "Hydrocortisone Compounded",
    "Hydroxyzine",
    "Hydroxyzine HCl Compounded",
    "Hygena Scoop",
    "HylaMAX",
    "Hylox",
    "Hyper Pet",
    "Hyperbiotics",
    "Hyperflite",
    "Hyponic",
    "I and Love and You",
    "Iams",
    "Ibiyaya",
    "IBK Doggies",
    "Iceland Pure Pet Products",
    "Icelandic+",
    "Iconic Pet",
    "ICU Medical",
    "Ideal Pet Products",
    "iFetch",
    "iGroom",
    "Ikaria",
    "Illumiseen",
    "Imatinib Compounded",
    "Impact Dog Crates",
    "Imperial Cat",
    "Inaba",
    "Inception",
    "InClover",
    "Incurin",
    "Indigenous Pet Products",
    "Indipets",
    "Industrial Puppy",
    "Infinite Pet Life",
    "Infinity",
    "Injoya",
    "Innovative Pet Lab",
    "INSE",
    "Inspire",
    "Inspire Naturals",
    "Insta360",
    "INSTACHEW",
    "Instinct",
    "IntelliLeash",
    "Interceptor",
    "Interceptor Plus",
    "International Veterinary Sciences",
    "Internet's Best",
    "Inukshuk",
    "Invenho",
    "INVIROX",
    "Invisible Fence",
    "Ion Fusion",
    "ION* Intelligence of Nature",
    "iPet",
    "iPets",
    "iPupPee",
    "IRIS",
    "iRobot",
    "Isle of Dogs",
    "ISlide",
    "Isoxsuprine HCl Compounded",
    "Itraconazole",
    "IV Needleless",
    "IV Set",
    "Ivation",
    "Iverhart Max",
    "Iverhart Plus",
    "Ivermectin Compounded",
    "IZOD Pet",
    "JAC Pet Nutrition",
    "Jack & Pup",
    "Jack PetPals",
    "Jackson Galaxy",
    "Jackson Galaxy Solutions",
    "jansno",
    "Jasper",
    "Jax & Cali",
    "Jax and Bones",
    "Jazwares",
    "JDS",
    "Jeffers",
    "JEJOU DOG",
    "Jespet",
    "JESSICA SIMPSON",
    "Jiby Dog Crew",
    "Jiminy's",
    "Jinx",
    "JOEJOY",
    "Joint MAX",
    "Jokari",
    "Jolly Pets",
    "JONES Craft Soda for Dogs",
    "JorVet",
    "Joyride Harness",
    "Julius-K9",
    "Jumbl Pets",
    "Jungle Calling",
    "Junior Mints",
    "JustFoodForDogs",
    "JW Pet",
    "JWalker Dog",
    "K&H Pet Products",
    "K-BroVet",
    "K-Plus",
    "K1 Pet Design",
    "K9 Advantix",
    "K9 Advantix II",
    "K9 Ballistics",
    "K9 Explorer",
    "K9 Innovations",
    "K9 Kennel Boss",
    "K9 Natural",
    "K9 Nature Supplements",
    "K9 POWER",
    "K9 Select",
    "K9 Sport Sack",
    "K9warehouse",
    "KADTC",
    "KAMABOKO",
    "Kanata On Demand",
    "Kangaroo",
    "Kanine",
    "Karoo Wild",
    "KASIKS",
    "Kate Spade New York",
    "Katziela",
    "Kay Berry",
    "Kayode",
    "KBroVet-CA1",
    "Keet",
    "Kenalog",
    "Kenchii",
    "KennelMaster",
    "Kenneth Cole",
    "Kensie",
    "Kent / Blue Seal",
    "KetoChlor",
    "Ketoconazole",
    "Ketoconazole Compounded",
    "Ketogenic Pet Food",
    "KetoNatural",
    "Ketorolac",
    "Kibbles 'n Bits",
    "KidCo",
    "KIDS 'N' PETS",
    "Kiku Handmade",
    "kin+kind",
    "Kinetic",
    "King Kanine",
    "King Lou",
    "Kingdom Pets",
    "Kismet",
    "KlearOtic",
    "Kodiak Naturals",
    "KOHA",
    "Koko Genetics",
    "Kona's Chips",
    "KONG",
    "KONG H2O",
    "KONG Retractable",
    "KONG Sport",
    "KOPEKS",
    "Kradle",
    "Kseroo",
    "Kuoser",
    "Kurgo",
    "Kylinsure",
    "KZLAA",
    "L.L.Bean",
    "La-Z-Boy",
    "Laazar",
    "Laboflex",
    "Labra",
    "Lactulose",
    "Lafeber",
    "LaiFug",
    "Lambwolf",
    "Lanana Creek Farms",
    "Lantus",
    "Lasko",
    "Latanoprost",
    "Lax-Aire",
    "Lazer Brite",
    "Lazy Dog Lounger",
    "Lealchum",
    "Leash Boss",
    "Leflunomide Compounded",
    "Left Coast Performance",
    "Legitpet",
    "LEMBERI",
    "Lennox",
    "Lennypads",
    "LESOTC",
    "Lesure",
    "LesyPet",
    "Levamisole Compounded",
    "Levetiracetam",
    "Levetiracetam Compounded",
    "LEVOIT",
    "Lexelium",
    "LFC PETS",
    "Li'l Pals",
    "Lick Lick Pad",
    "LickiMat",
    "Licks",
    "Lidocaine",
    "Life Essentials",
    "Life Extension",
    "LIFE IS GOOD",
    "Lifekey",
    "Lifetime",
    "Lightvise",
    "Lil Monster Pets",
    "Lil' Bitz",
    "Lil' Paw",
    "Lil' Squirts",
    "LILIPRO",
    "Lillian Ruff",
    "Lilly Brush",
    "Link",
    "Linzy Toys",
    "Liquid Fence",
    "Liquid Health Pets",
    "Liquid Shocker",
    "Liquid-Vet",
    "Lisinopril",
    "Litterbox.com",
    "Little Hunter",
    "Little Loyals",
    "Littlearth",
    "Live Fine",
    "Livelong Healthy & Strong",
    "Lively Pets",
    "Liver Bits",
    "Lixit",
    "LIZEVINC",
    "Lomustine Compounded",
    "Longevity15",
    "LOOBANI",
    "Looney Tunes",
    "Loops 2",
    "Lord Jameson",
    "Lots of Love Pet Products",
    "Lotus",
    "Louie Living",
    "Lovin'Tenders",
    "Loving Pets",
    "LovMor",
    "Loyal Saints",
    "Loyalty Pet Products",
    "LubriSyn",
    "Lucky Dog",
    "Lucky Paworld",
    "Lucky Premium Treats",
    "Lucky Pup",
    "Luckylala",
    "Luckypets",
    "LuckyTail",
    "Lucy & Co.",
    "Lucy Pet Products",
    "LuftPets",
    "Lumabone",
    "LumaSoothe",
    "Lumi Pawtners",
    "LupinePet",
    "LvLrister",
    "Lysodren",
    "M BARCLAY INC",
    "Mad Dog Products",
    "MAEV",
    "Magic Fabric",
    "Magic Mesh",
    "Maintain Chunks",
    "Maison FurRéal",
    "Majestic Bombay",
    "Majestic Pet",
    "Makondo Pets",
    "Mal-A-Ket",
    "Malabi",
    "MalAcetic",
    "Malaseb",
    "Malden International Designs",
    "MALOROY",
    "Mambe",
    "Mammoth",
    "Maptote",
    "Marbofloxacin",
    "Marbofloxacin Compounded",
    "Marly & Dan",
    "Maropitant Citrate",
    "Maropitant Compounded",
    "Marsh Dog",
    "Martha Stewart",
    "Martin's",
    "Marvel",
    "Maslow",
    "Master Equipment",
    "Master Grooming Tools",
    "Mattie's Treats",
    "Mau",
    "Max & Molly",
    "Max and Neo Dog Gear",
    "Max Power Planet",
    "Max's Closet",
    "maxbone",
    "MAXI/GUARD",
    "maxxipaws",
    "Mayday",
    "Mayitwill",
    "Mazuri",
    "Meaty Treats",
    "MECO",
    "MEDI CRUNCH",
    "MediNatura",
    "Medipaw",
    "Medline",
    "Medrol",
    "MEGAPAWS",
    "Megestrol",
    "MEIQIHOME",
    "Mela-Vet",
    "Melanie Newman",
    "Meloxicam",
    "Meloxicam Compounded",
    "Meloxidyl",
    "Melphalan Compounded",
    "Mendota Pet",
    "Mendota Products",
    "Merck",
    "Merrick",
    "Merry Products",
    "Metacam",
    "Methazolamide Compounded",
    "Methimazole",
    "Methimazole Compounded",
    "Methocarbamol",
    "Methocarbamol Compounded",
    "Methylprednisolone",
    "Metoclopramide",
    "Metoclopramide Compounded",
    "Metronidazole",
    "Metronidazole Compounded",
    "MetroVac",
    "MewooFun",
    "Miaustore",
    "Michu",
    "MiconaHex+Triz",
    "Miconazole",
    "MicraVet",
    "Midamox",
    "MidWest",
    "MidWest Homes for Pets",
    "Miele",
    "Mighty",
    "Mighty Paw",
    "Mighty Tuff",
    "Milbeguard",
    "Milk Thistle Compounded",
    "Milk Thistle/SAMe Compounded",
    "Milk Thistle/SAMe/Ursodiol Compounded",
    "Milk-Bone",
    "Millers Forge",
    "Milo's Kitchen",
    "Mimi Green",
    "Mimofpet",
    "Mina Victory",
    "Mini Educator",
    "Minnidip",
    "Minocycline",
    "Minties",
    "Miracle Care",
    "Miracle Vet",
    "Mirapet",
    "Mirtazapine",
    "Mirtazapine Compounded",
    "Miss Nelly's",
    "Mission Farms",
    "MisterMax",
    "MitoMax",
    "Mitotane Compounded",
    "Mobile Dog Gear",
    "MODERN THREADS",
    "Modign",
    "Modulis",
    "Moe's Healthy Pets",
    "Moist & Meaty",
    "Moko",
    "Molly Mutt",
    "Mometamax",
    "Mometavet",
    "MON2SUN",
    "Monoject",
    "Monster K9 Dog Toys",
    "Moochie",
    "Moots",
    "Mora Pets",
    "Mosaic",
    "Moso Natural",
    "Mossy Oak",
    "Mount Ara",
    "Mountain Plains All American Pet Treats",
    "Mountainsmith",
    "MPA",
    "Mr. Groom",
    "Mr. Peanut's",
    "Mr. Smiley Pug",
    "Mrs. Meyer's",
    "Mud Pie",
    "Mud River",
    "Muddy Mat",
    "Muenster",
    "Muffin's Halo For Blind Dogs",
    "Multipet",
    "Mupirocin",
    "Muricin",
    "Mush Buddies",
    "Musher's Secret",
    "Mutt Mitt",
    "Muttluks",
    "MuttsKickButt",
    "My Dog Nose It!",
    "My Doggy Place",
    "My Pet's Comb",
    "MycoDog",
    "Mycogen",
    "Mycophenolate",
    "Mycophenolate Mofetil Compounded",
    "MyEcoWorld",
    "myfamily",
    "MYOS",
    "MyPet",
    "Myristin",
    "N-Bone",
    "Naavi",
    "Naltrexone HCl Compounded",
    "NANAKI",
    "Nandi",
    "Nandog",
    "NASCAR",
    "Natemia",
    "National Blue",
    "Native",
    "Native Pet",
    "Natoo",
    "NatrixOne",
    "Natur-Yeast",
    "Natura Petz Organics",
    "Natural Balance",
    "Natural Care",
    "Natural Dog Company",
    "Natural Farm",
    "Natural Light",
    "Natural Pet",
    "Natural Pet Partners",
    "Natural Rapport",
    "Natural Wag",
    "Naturally Wild Pet Treats",
    "Nature Gnaws",
    "Nature's Advantage",
    "Nature's Aid",
    "Nature's Deli",
    "Nature's Diet",
    "Nature's Farmacy",
    "Nature's HUG",
    "Nature's Logic",
    "Nature's Miracle",
    "Nature's Protection",
    "Nature's Pure Edge",
    "Nature's Recipe",
    "Nature's Specialties",
    "Naturel Promise",
    "NaturPet",
    "NaturVet",
    "Navus Naturals",
    "Neakasa",
    "Neater Pets",
    "Necoichi",
    "NEEZUKAR",
    "Nellie's Clean",
    "Neo-Poly",
    "Neo-Poly-Bac",
    "Neo-Poly-Dex",
    "Neo-Predef",
    "NeoAlly",
    "Neogen",
    "Neomycin Sulfate Compounded",
    "NephroMax",
    "Nerf Dog",
    "New Age Pet",
    "New Earth Soy",
    "Newman's Own",
    "NexGard",
    "NexGard PLUS",
    "Next Level Super Premium Pet Food",
    "NextStar",
    "Nicole Miller",
    "Nina Ottosson by Outward Hound",
    "Nina Woof",
    "NineStars",
    "Nite Ize",
    "Niubya",
    "Nixall",
    "Nixit",
    "No Natz",
    "Noah & Paw",
    "NOBL",
    "Nocciola",
    "Nolvasan",
    "Nom Nom",
    "NoMo Nausea Bands",
    "NonoPets",
    "NonScents",
    "Nootie",
    "Nordic Naturals",
    "Nordic Pure",
    "Normosol-R",
    "North States",
    "Novolin",
    "Now Fresh",
    "NOW Pets",
    "Nulo",
    "Nummy Tum-Tum",
    "Nusentia",
    "Nutramax",
    "Nutrena",
    "Nutri Chomps",
    "Nutri-Vet",
    "Nutricost Pets",
    "NutriScan",
    "Nutrish",
    "NutriSource",
    "NutriVed",
    "Nutro",
    "Nutties",
    "NWC Naturals",
    "Nylabone",
    "Nystatin",
    "Ocean Plastic by PT",
    "Oculenis",
    "OdoBan",
    "Odormute",
    "OdorXit",
    "Off Leash",
    "Ofloxacin",
    "OH NORMAN",
    "Oh You Lucky Dog!",
    "OIC Pet",
    "Old Mother Hubbard",
    "OleyHemp",
    "Omega Fields",
    "Omega Paw",
    "Omega-Caps",
    "Omeprazole Compounded",
    "OmniPet",
    "Ondansetron",
    "Ondansetron Compounded",
    "One for Pets",
    "OneIsAll",
    "OneTigris",
    "Onguard Plus",
    "ONIZOOMI",
    "OOPSDOGGY",
    "Operation Good Boy",
    "OphtHAvet",
    "Optimeal",
    "Optimmune",
    "Optixcare",
    "Ora-Clens",
    "Oral Syringes",
    "Oralade",
    "Oratene",
    "OraVet",
    "Orbax",
    "OrgaNOMics",
    "ORIJEN",
    "Orivet",
    "ororo",
    "Ortho",
    "Orvis",
    "Oster",
    "Osurnia",
    "Other Half",
    "Otomax",
    "Otterly Pets",
    "Our Name is Mud",
    "OurPets",
    "OUT!",
    "Outback Hound",
    "Outback Jack",
    "Outward Hound",
    "Ownpets",
    "OxiClean",
    "Oxyfresh",
    "Ozark Pet",
    "P.L.A.Y. Pet Lifestyle and You",
    "P.T. Supply Co",
    "P.T. Supply Co.",
    "P2 Probiotic Power",
    "Pacific Pups Rescue",
    "Pack Approved",
    "PAIKKA",
    "PaiPaitek",
    "Palladia",
    "Palmer's",
    "Palz&Co",
    "Pamper Like Paris",
    "Pan-tenex",
    "Panacur",
    "PanaKare Plus",
    "PancrePlus",
    "Papa Bow Wow Wholesome Treats",
    "Paramount Pet Health",
    "Paris Hilton Pet",
    "Parisian Pet",
    "Park Life Designs",
    "Particular Paws",
    "Patchwork Pet",
    "PatiencET",
    "Patika Pets",
    "PATPET",
    "Paul Mitchell Pet",
    "Pavilion",
    "PAW",
    "Paw & Pantry",
    "Paw Inspired",
    "Paw Mountain",
    "Paw Plunger",
    "Paw Prints",
    "Paw Ready",
    "Paw Thaw",
    "PAW5",
    "PAWBEE",
    "Pawbo",
    "Pawbola",
    "PawBrands",
    "Pawfect",
    "Pawfect Pets",
    "PawfectChew",
    "PawFlex",
    "Pawfume",
    "PawFurEver",
    "Pawfy",
    "PawHut",
    "Pawland",
    "Pawlife",
    "PawLove",
    "Pawlymorph Pet Toys",
    "PawMedica",
    "PawPail",
    "PawPerfect",
    "Pawple",
    "Pawprints Left by You",
    "Pawprints Remembered",
    "PAWS & BONES",
    "Paws & Decor",
    "Paws & Pals",
    "Pawscout",
    "Pawse",
    "Pawseat",
    "Pawshelf",
    "PawSono",
    "PawSpa",
    "PawsPik",
    "Pawssups",
    "Pawstruck",
    "Pawsync",
    "PawTides",
    "Pawtitas",
    "PawTrk",
    "PAWTY TOYS",
    "Pawview",
    "Pawward",
    "Pawz",
    "Pawzler",
    "peaksNpaws",
    "PeakTails",
    "PEANUTS",
    "Peanuts",
    "Peanuts Snoopy",
    "Pearhead",
    "Pebblebee",
    "Pebot",
    "Pecute",
    "Pedigree",
    "PeeDar",
    "Peeps",
    "Pendleton",
    "Penicillamine Compounded",
    "Penn-Plax",
    "Pennington",
    "Penthouse Paws",
    "Pentoxifylline",
    "Pentoxifylline Compounded",
    "Percorten-V",
    "Perfect Coat",
    "Perfect Pet Products",
    "Performacide",
    "Pershyra",
    "Pet 'n Shape",
    "Pet Acoustics",
    "Pet Adobe",
    "Pet Botanics",
    "Pet Center",
    "Pet Dream House",
    "Pet Evac Pak",
    "Pet Eyez",
    "Pet Factory",
    "Pet Fit For Life",
    "Pet Gear",
    "Pet Genie",
    "Pet Gifts USA",
    "Pet Greens",
    "Pet Head",
    "Pet Health Pharma",
    "Pet Health Solutions",
    "Pet Healthy Brands",
    "Pet Honesty",
    "Pet House",
    "Pet Jerky Factory",
    "Pet Krewe",
    "Pet Life",
    "Pet Life Unlimited",
    "Pet Magasin",
    "Pet Marvel",
    "Pet MasterMind",
    "Pet MD",
    "PET N PET",
    "Pet Naturals",
    "Pet Odor Exterminator",
    "Pet OTC",
    "Pet Pain Away",
    "Pet Parents",
    "Pet Passion",
    "Pet Piller",
    "Pet Protect",
    "Pet Qwerks",
    "Pet Releaf",
    "Pet Releaf Rituals",
    "Pet Remedy",
    "Pet Republique",
    "Pet Shop by Fringe Studio",
    "Pet Silk",
    "Pet Standard",
    "Pet Support Systems",
    "PET TAO",
    "Pet Teezer",
    "Pet Ultimates",
    "Pet Vet Products",
    "Pet Wellbeing",
    "Pet Zone",
    "Pet's Choice",
    "Pet's Choice Pharmaceuticals",
    "Pet-Pourri",
    "Pet-Tabs",
    "Pet-Temp",
    "Pet-Tinic",
    "PetAble",
    "PetAg",
    "PetAlive",
    "PetAmi",
    "PetArmor",
    "Petaxin",
    "Petazy",
    "PetBeing",
    "Petbobi",
    "PetBrush by WetBrush",
    "PetCakes",
    "PetChatz",
    "Petcube",
    "PetCultures",
    "Petcurean Summit",
    "Petdiary",
    "Petfon",
    "PetFusion",
    "PETGEEK",
    "PETiCO",
    "PETIPET",
    "Petique",
    "PetJoy",
    "Petkin",
    "PetKind",
    "PETKIT",
    "Petknowledgy by Spunky Pup",
    "PetKORE",
    "PetLab Co.",
    "PetLab Extractos",
    "Petlibro",
    "Petlou",
    "PetLovers",
    "PetLuv",
    "Petmate",
    "PetMedics",
    "Petnatics",
    "petnc",
    "PetNF",
    "PetO'Cera",
    "Petology",
    "Petopia",
    "Petosan",
    "PetPlate",
    "Petpost",
    "PetPrevea",
    "PetPro",
    "PetRageous Designs",
    "Petralyte",
    "PetriMins",
    "Pets First",
    "Pets Know Best",
    "Pets Prefer",
    "Pets So Good",
    "PetSafe",
    "Petscosset",
    "PetScy",
    "Petsfit",
    "PETSHOP BY FRINGE STUDIO",
    "PetSilver",
    "Petsmile",
    "Petsmont",
    "PetSnowy",
    "Petsonik",
    "PetsPrefer",
    "PetSpy",
    "Petstages",
    "PetSTEP",
    "PetStrips",
    "PetsWorld",
    "Petterm",
    "PetTest",
    "Petthrive",
    "Pettsie",
    "PetVet Medic",
    "PetZu",
    "Phelps Wellness Collection",
    "Phenoxybenzamine HCl Compounded",
    "Phenylpropanolamine Hydrochloride",
    "PhiBro",
    "Phoenix",
    "Phycox",
    "Pidan",
    "PiFi",
    "Piggy Poo and Crew",
    "Pill Buddy Naturals",
    "Pilocarpine",
    "Pimobendan Compounded",
    "Pink Papyrus",
    "Pioneer Pet",
    "Piroxicam",
    "Piroxicam Compounded",
    "Pistachio Brands",
    "Pixar",
    "Plano Paws",
    "Platinum Pet Treats",
    "Platinum Pets",
    "Plato",
    "Play 365",
    "Playfield",
    "Playology",
    "PlaySAFE",
    "PLS Birdsong",
    "Plush Paws Products",
    "Pogi's Pet Supplies",
    "PointPet",
    "PoisePup",
    "Poke's",
    "Pokemon",
    "Pokpet",
    "Polkadog",
    "POM Pet",
    "Ponazuril Compounded",
    "Pooch Approved Products",
    "Pooch Cake",
    "Pooch Creamery",
    "Pooch Selfie",
    "Poochie Butter",
    "Poochie Chews",
    "Poochie-Pets",
    "PoochieBells",
    "PooPail by GoodWag",
    "POOPH",
    "poopooh",
    "PoopShark",
    "Pork Chomps",
    "PortionPro Rx",
    "Portland Pet Food Company",
    "Posatex",
    "POSE PETS",
    "Potaroma",
    "Potassium Bromide Compounded",
    "Potassium Citrate Compounded",
    "Pounce + Fetch",
    "Power House",
    "Power Walker",
    "Prairie Dog",
    "Prana Pets",
    "Praziquantel",
    "Praziquantel Compounded",
    "Prazosin",
    "Prazosin Compounded",
    "Precious Tails",
    "Precise Cut",
    "Precision Pet Products",
    "Prednisolone",
    "Prednisolone Compounded",
    "Prednisone",
    "Prednisone Compounded",
    "Premier Pet",
    "Premier Pet Steps",
    "Previcox",
    "Prevue Pet Products",
    "Pride+Groom",
    "Prima Pets",
    "Primal",
    "Primalvore",
    "Primetime Petz",
    "Primidone",
    "Primitives By Kathy",
    "Prinz",
    "PRN Pharmacal",
    "Pro",
    "Pro Pac",
    "Pro-Coat Grooming",
    "Pro-Sense",
    "ProBiora",
    "Probios",
    "ProDen",
    "ProDogg",
    "Professional Pet Products",
    "Proflora",
    "Proin",
    "Proin ER",
    "Project Hive Pet Company",
    "Project Paws",
    "Project Sudz",
    "Promika",
    "ProSelect",
    "Protecto",
    "ProZinc",
    "PS KOREA",
    "Pup Choice",
    "Pup Ice",
    "Pup-Peroni",
    "PUPCA",
    "PupCorn",
    "Pupford",
    "PupGrade",
    "pupp st.",
    "Puppia",
    "Puppington",
    "PupPod",
    "Puppy Chow",
    "Puppy Go Potty",
    "Puppy Pan",
    "Puppylocks",
    "PUPROAR",
    "PupSip",
    "Pupzle",
    "Pur Luv",
    "Pura",
    "Puralube",
    "Pure & Simple Pet",
    "Pure + Good",
    "Pure and Natural Pet",
    "PureAyre",
    "PureBites",
    "Purefy",
    "Pureluxe Elite Nutrition",
    "PureSnacks",
    "Purina Beneful",
    "Purina Beyond",
    "Purina ONE",
    "Purina Petivity",
    "Purina Pro Plan",
    "Purina Pro Plan Veterinary Diets",
    "Purina TBONZ",
    "Purina Twistables",
    "Purpose",
    "Purrdy Paws",
    "Purrfect Portal",
    "PuzzleFeeder",
    "PXZEE",
    "QALO",
    "QT Dog",
    "Quarto Publishing",
    "Quellin",
    "Quick-Tag",
    "Rabbit Air",
    "Rachael Ray Nutrish",
    "RADIUS",
    "Rae Dunn",
    "Ramard",
    "Raw Paws",
    "Raypet",
    "Razzles",
    "RC Pets",
    "Ready Pet Go",
    "Real Hide",
    "Real Mushrooms",
    "Realtree",
    "Rebel Dawg",
    "Reconcile",
    "Red Dingo",
    "Red Rocket",
    "Redbarn",
    "Rederox",
    "Redmon",
    "Redonyl",
    "Regal Pet Foods",
    "Regalo",
    "Reggie",
    "Relax Dog",
    "RelaxoPet",
    "Relief",
    "RELIQ",
    "ReMATRIX",
    "Remedi Animal Solutions",
    "Remington",
    "Remy's Kitchen",
    "Rena's Recipe",
    "RenaKare",
    "RenaPlus",
    "RenewedPet",
    "Reolink",
    "Replenish",
    "Resco",
    "Rescue Remedy",
    "Reserve",
    "Resolve",
    "ResQ Organics",
    "Restology",
    "RestoraPet",
    "Resvantage",
    "Retrospec",
    "Revolt",
    "Revolution",
    "Rewardables",
    "Rex Specs",
    "REÁL MESA",
    "Richard's Organics",
    "Richell",
    "Ridge Creek",
    "Rifampin",
    "RIFRUF",
    "Rilexine",
    "Riley's",
    "Rimadyl",
    "Ring",
    "Ring Out",
    "Rinse Ace",
    "Rinseroo",
    "Roam",
    "Roborock",
    "Rocco & Roxie Supply Co.",
    "Rocket & Rex",
    "Rockster",
    "Rogue Pet Science",
    "Rooted Owl",
    "Roscoe's Pet Products",
    "Rowan",
    "Royal Animals",
    "Royal Canin",
    "Royal Canin Veterinary Diet",
    "Royal Cat Boutique",
    "Royal Ramps",
    "Rubie's Costume Company",
    "Rubit!",
    "Rucal Pets",
    "Ruff & Whiskers",
    "Ruff & Whiskerz",
    "Ruff 'N Ruffus",
    "RUFF by Lillian Ruff",
    "Ruff Dawg",
    "Ruff Greens",
    "RUFFIN' IT",
    "Ruffsack",
    "Ruffwear",
    "Rufus & Coco",
    "Ruji Naturals",
    "Rustic Kitchen",
    "RX 4 Pets",
    "Rx Vitamins",
    "RYPetmia",
    "S-Adenosyl Methionine (SAMe) Compounded",
    "Sabrini's Royal Treats",
    "Safari",
    "Safe Paw",
    "Safe-Guard",
    "SafePaws",
    "Safety 1st",
    "Safety-Sport",
    "SafetyPUP XD",
    "Salix",
    "Sam's Pets",
    "Sammy's Shiny Coat",
    "Samsung",
    "Sassy Woof",
    "SATELLAI",
    "Savannah Pet Food",
    "Savory Prime",
    "Scamper & Co",
    "Scandinavian Pet",
    "Scaredy Cut",
    "Schirmer",
    "Scooby Doo",
    "Scoochie Pet",
    "Scoopi Doo",
    "Scotch & Co",
    "Scotch-Brite",
    "Scott Pet Guard",
    "Scrubby",
    "Scrubby Tails",
    "Seal It",
    "Seat Armour",
    "Secnidazole Compounded",
    "Secure",
    "SecureAway",
    "See Spot Run",
    "Seedshub",
    "Selamectin",
    "Selarid",
    "Selegiline",
    "Selegiline HCl Compounded",
    "Senergy",
    "Sentinel",
    "Sentinel Spectrum",
    "Sentry",
    "Seresto",
    "Sergeant's",
    "Serta",
    "Sertraline Compounded",
    "Shameless Pets",
    "Shandus",
    "Sharf",
    "Shark",
    "Sharper Image",
    "Sharps Container",
    "Shed Defender",
    "Shed-X",
    "SHELANDY",
    "Shele",
    "ShelterLogic",
    "Shepherd Boy Farms",
    "Shernbao",
    "Sherpa",
    "Sherry Kline Pet Collection",
    "Shinola",
    "Shirley K's",
    "Shop Care",
    "ShopInstaPets",
    "ShotClockr",
    "ShowerShroom",
    "Side By Side",
    "Signature Housewares",
    "Sildenafil",
    "Sildenafil Compounded",
    "Sileo",
    "SiliDog",
    "Silly Squeakers",
    "Silpat",
    "Silver Biotics",
    "Silver Honey",
    "Silver Sulfadiazine",
    "SilymarinAdvanced",
    "Simparica",
    "Simparica Trio",
    "Simple Food Project",
    "Simple Green",
    "Simple Solution",
    "SimpleSource",
    "Simplicef",
    "Simply Wags",
    "Simply Wild",
    "SinkShroom",
    "Sitka Farms",
    "SkinSmart",
    "Skout's Honor",
    "Sleepy Pet",
    "Sleepypod",
    "SLIDE ha+ Advanced Joint Lubrication",
    "Slobber Threads",
    "SlowTon",
    "Small Pet Select",
    "Smallbatch Pets",
    "Smart Cookie Barkery",
    "Smart Paws",
    "Smart Pet Love",
    "SmartBones",
    "Smelleze",
    "SMELLRID",
    "Smells Begone",
    "Smiling Paws Pets",
    "smith&burton",
    "Smokehouse",
    "SMONTER",
    "SMZ TMP",
    "Snack 21 Treats",
    "Snaks 5th Avenchew",
    "Snicky Snaks",
    "Snif-Snax",
    "Snoozer Pet Products",
    "Snoozzy",
    "Snorehound",
    "Snow Joe",
    "Snugarooz",
    "Snuggle Puppy",
    "SodaPup",
    "Sodium Bicarbonate",
    "Sodium Chloride",
    "Soft Claws",
    "Soft Touch Collars",
    "Soggy Doggy",
    "Sojos",
    "Solid Gold",
    "Sonic Power",
    "Soos Pets",
    "Soos Wellness",
    "Sotalol",
    "Southern Therapy Candles",
    "Sovereign Silver Pets",
    "Sparkles Home",
    "Special Breed",
    "Special FX",
    "Speckle & Spot by Ore' Originals",
    "Spectracide",
    "SpectraShield",
    "Spirich",
    "Spironolactone",
    "Spironolactone Compounded",
    "SpongeBob",
    "Sporn",
    "SportDOG",
    "SPORTMiX",
    "SportPet Designs",
    "Sportsman's Pride",
    "Spot",
    "Spot Farms",
    "SpotOn Fence",
    "Spotty",
    "Sprankles",
    "Spray & Go",
    "Springland",
    "Sprinkle & Sweep",
    "Spunky Pup",
    "SpunkyJunky",
    "SquarePet",
    "Squishface",
    "Squishmallows",
    "Squishy Face Studio",
    "Stance Equitec",
    "STAR WARS",
    "Star Wars by Fetch for Cool Pets",
    "Starmark",
    "Stashios",
    "Stazko",
    "Steam & Go",
    "SteelDog USA",
    "Stella & Chewy's",
    "Step Above Proteins",
    "Stewart",
    "Stink Free",
    "StopShroom",
    "Stratford Animal Health",
    "Strawfield Pets",
    "StrellaLab",
    "Stunt Puppy",
    "Sublime",
    "SUCHGOOD",
    "Sucralfate",
    "Sucralfate Compounded",
    "Suitical",
    "Sulfasalazine",
    "Sulfodene",
    "Sulfox",
    "Summer by Ingenuity",
    "Summit Animal Health",
    "Sunburst",
    "SunGrow",
    "Sunny Tails",
    "Super Snouts",
    "Super Wags",
    "SuperCan Bully Sticks",
    "Supet",
    "Supreme Source",
    "Sure Petcare",
    "SureComfort",
    "SureFeed",
    "SureFlap",
    "Surf City Pet Works",
    "Surgi Snuggly",
    "Surolan",
    "Swederma",
    "Sweet Paws",
    "SwiftPaws",
    "Syner-G",
    "Synotic",
    "T8 Keto",
    "Tacrolimus Compounded",
    "Tail Bangers",
    "Tailr",
    "Taily",
    "Tamsulosin Hydrochloride",
    "Tartar Shield",
    "Taste of the Wild",
    "Tauro Pro Line",
    "Tavo Pets",
    "Team Dog",
    "Team Treatz",
    "TechNiche International",
    "TEEF!",
    "Teenage Mutant Ninja Turtles",
    "Telmisartan Compounded",
    "Temaril-P",
    "Tender & True",
    "Terbinafine Compounded",
    "Terbutaline",
    "Terbutaline Sulfate Compounded",
    "Terrabone",
    "TerraMax",
    "Terramycin",
    "Territory",
    "Terry Naturally Animal Health",
    "Terumo",
    "Tetracycline HCl Compounded",
    "TevraPet",
    "Texas Pet Company",
    "The Absorber",
    "The Avalon Society",
    "The Blissful Dog",
    "The Company of Animals",
    "The Country Butcher",
    "The Easy-Clean Water Bowl",
    "The Granville Island Pet Treatery",
    "The Green Dog",
    "The Green Pet Shop",
    "The Honest Kitchen",
    "The Humane Society",
    "The Key Chain Urn Company",
    "The Lazy Dog Cookie Co.",
    "The License House",
    "THE LICKER STORE",
    "The Missing Link",
    "The Nature Company",
    "The New Zealand Natural Pet Food Co.",
    "The Original Poop Bags",
    "The Paws",
    "The Pets Table",
    "The Petz Kitchen",
    "The Rawhide Express",
    "The Refined Feline",
    "The Stuff",
    "The Tick Patrol",
    "The Treat Shack",
    "The Vet's Dog",
    "The Virtually Indestructible Ball",
    "The Weens",
    "The Worthy Dog",
    "Theophylline",
    "Theophylline Compounded",
    "this and that Canine Company",
    "This Dog's Life",
    "Thompson's Candle Co.",
    "Thornell",
    "ThorneVET",
    "Three Dog Bakery",
    "Thule",
    "ThunderBites",
    "ThunderCap",
    "ThunderCloud",
    "ThunderCover",
    "ThunderEase",
    "ThunderEssence",
    "ThunderLeash",
    "ThunderShirt",
    "ThunderSnap",
    "ThunderWunders",
    "Thyro-Tabs",
    "Tibetan Dog Chew",
    "Tibetan Dog Treats",
    "TiCK MiTT",
    "TickCheck",
    "Tickless",
    "Tikaton",
    "Tiki Dog",
    "Tilted Barn Pet Company",
    "Timberdog",
    "TIMHAKA",
    "Timolol",
    "Tineco",
    "Titan",
    "Titan Casket",
    "Tobramycin",
    "TOBYDIC",
    "Toceranib Compounded",
    "Toltrazuril Compounded",
    "Tomlyn",
    "Tommy Bahama Pet",
    "Tommy Hilfiger",
    "Tootsie Roll",
    "Top Dog",
    "Top Dog Chews",
    "Top Performance",
    "TopDog Health",
    "Toptrees",
    "Torsemide",
    "Torus Pet",
    "Total Feeds",
    "Totally Wags",
    "Touchdog",
    "Tough Stuff",
    "Tourna",
    "Tracki",
    "Traction Magic",
    "Tractive",
    "Trail Hound Pet Supply Co.",
    "Trainer Dog Collar",
    "Training",
    "TranQuil",
    "Tranquil Tails",
    "Travco Products",
    "Travel Cat",
    "Trazodone",
    "Trazodone HCl Compounded",
    "Treatibles",
    "Treatly",
    "Tresaderm",
    "Tri-Heart Plus",
    "Triamcinolone Acetonide",
    "Tribe Socks",
    "Trick or Snack",
    "Tricky Treat",
    "TRIFECTA LLC",
    "Trifexis",
    "Trill Paws",
    "Trilostane Compounded",
    "Trimeprazine/Prednisolone",
    "TRINITY",
    "TriNova",
    "Triox",
    "Trisha Yearwood Pet Collection",
    "Triumph",
    "TRIXIE",
    "TrizCHLOR",
    "TrizEDTA",
    "TrizULTRA",
    "TropiClean",
    "TRP",
    "TRP-Chondro-FLEX",
    "Trudell Medical International",
    "True Acre Foods",
    "True Leaf",
    "True Tails",
    "True Touch",
    "TrueBlue Pet Products",
    "TruRanch",
    "Trusted Pets",
    "Trusty Paws",
    "TrustyPup",
    "TubShroom",
    "Tuenne",
    "Tuff Mutt",
    "Tuffy's",
    "tuft + paw",
    "TUG",
    "Tugzelle",
    "Tulane's Closet",
    "Tumbo",
    "Tweezerman",
    "Twin Springs",
    "Two By Two",
    "Two Tails Pet Company",
    "Tylan",
    "Tylee's",
    "Tylosin",
    "Tylosin Compounded",
    "Ubbi",
    "UltiCare VetRx",
    "Ultimate Pet Nutrition",
    "Ultimates",
    "Ultra Chewy",
    "Ultra Collection",
    "Ultra Joint",
    "Ultra Paws",
    "UltraCruz",
    "Uncharted Supply Co",
    "Under the Weather",
    "Unipaws",
    "United Solutions",
    "Up Country",
    "UpCard-CA1",
    "Uproot Clean",
    "UPSKY",
    "Urine Gone",
    "Urine Off",
    "Ursodiol",
    "Ursodiol Compounded",
    "US ARMY",
    "USA-K9",
    "V-Dog",
    "Vacqueen",
    "Van Beek Natural Science",
    "Van Ness",
    "Vapur",
    "Vectra",
    "VEDCO",
    "Veehoo",
    "Venison Joe's",
    "Vera Bradley",
    "Vet Aid",
    "Vet Basics",
    "Vet Organics",
    "Vet Worthy",
    "Vet's Best",
    "Vet-Temp",
    "Vetality",
    "VetClassics",
    "Vetericyn",
    "Veterinary Formula Clinical Care",
    "Veterinary Formula Smart Coat Complex",
    "Veterinary Formula Smart Vitality",
    "Veterinary Select",
    "VetHemp",
    "VetIQ",
    "Vetivex",
    "Vetmedin",
    "Vetmedin-CA1",
    "Vetnique Labs",
    "VetOne",
    "Vetoquinol",
    "Vetoryl",
    "Vetpen",
    "VETRADENT",
    "VETRESKA",
    "Vetri-CAL",
    "VETRIMAX",
    "VetriScience",
    "Vets Preferred",
    "VetSmart Formulas",
    "Vetsulin",
    "VetWELL",
    "Vial Safe For Pets",
    "Vibeful",
    "VICTOR",
    "Vila",
    "Vintek Nutrition, LLC",
    "Viokase-V",
    "Viper",
    "Virbac",
    "Virbantel",
    "Visionary Pet Foods",
    "Vita Bone",
    "Vita-Jec",
    "Vita-Soothe",
    "Vita-Tabs",
    "VitaDog Nutrition",
    "Vitafur",
    "Vitakraft",
    "Vital Essentials",
    "Vital Pet Life",
    "Vital Pet Sciences",
    "Vital Planet",
    "Vitality Science",
    "Vitalize",
    "Vitamin B12",
    "Vitamin K1",
    "VIVIPAL",
    "Voluas",
    "Voriconazole Compounded",
    "VPS",
    "W&P",
    "W.Kleinberg",
    "WACKYwalk'r",
    "Wag and Wiggle",
    "WagAround Town",
    "Wagberry",
    "waggedy",
    "Waggin' Train",
    "Waggo",
    "Waggz",
    "Wags & Wiggles",
    "Wahl",
    "Walk 'n Train",
    "WALKABOUT",
    "Walkin Pets",
    "Walky Dog",
    "Wanderfound Pets",
    "Wanpy",
    "Wanpy Prime",
    "WAOWAO",
    "Wapiti Labs",
    "WARCAT",
    "Warner Bros",
    "Warren London",
    "WashBar",
    "Water & Woods",
    "WAUDOG",
    "Waveland Paws",
    "We Love Doodles",
    "WeatherBeeta",
    "WeatherTech",
    "Weaver Pet",
    "Wee Away",
    "Wee-Wee",
    "WellJoy",
    "Wellnergy Pets",
    "Wellness",
    "Weruva",
    "Wesley Nutraceuticals",
    "West Paw",
    "Wet Noses",
    "Wet Ones",
    "Wham-O",
    "WHIMZEES",
    "Whisker",
    "Whole Life",
    "Wholesome Pride Pet Treats",
    "Wholesomes",
    "Wholistic Pet Organics",
    "Wholly Pup",
    "WickedPup",
    "Wigzi",
    "Wild Acre Pet",
    "Wild Earth",
    "Wild Eats",
    "Wild One",
    "Wild Ranger",
    "WildHound",
    "Wildly Natural",
    "Win World",
    "Wingo Outdoors",
    "WINiPET",
    "Winnie Lou",
    "WINPRO Pet",
    "Wisdom Panel"
]

# Normalized brands (lowercase) for fast matching
NORMALIZED_BRANDS = [brand.lower() for brand in BRANDS]

# Create a mapping for quick lookup
BRAND_MAP = {normalized: original for normalized, original in zip(NORMALIZED_BRANDS, BRANDS)}

